kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-argo-deployment
  namespace: house-manager
  labels:
    app: frontend-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-argo
  template:
    metadata:
      labels:
        app: frontend-argo
    spec:
      containers:
        - name: frontend
          image: housemanager/frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
